<?xml version="1.0" encoding="utf-8"?>
<assembly name="skeleton"
          run-date="2015-06-05" run-time="18:34:41"
          configFile="none"
          time="0.047"
          total="2"
          passed="0"
          failed="2"
          skipped="0"
          environment="n/a"
          test-framework="golang">

    <class time="0.047" name="skeleton"
  	     total="2"
  	     passed="0"
  	     failed="2"
  	     skipped="0">

        <test name="TestError1"
          type="test"
          method="TestError1"
          result="Fail"
          time="0.00">
          <failure exception-type="go.error">
             <message><![CDATA[	main_test.go:10: something went wrong]]></message>
      	  </failure>
      	</test>

        <test name="TestError2"
          type="test"
          method="TestError2"
          result="Fail"
          time="0.00">
          <failure exception-type="go.error">
             <message><![CDATA[	main_test.go:14: something new went wrong]]></message>
      	  </failure>
      	</test>

    </class>

</assembly>
